"""Artifacts: the generated reports, the raw files, and a lazy predictions drill-down."""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st

from embbench.dashboard import loader, ui
from embbench.dashboard.state import selected_results


def render() -> None:
    ui.page_header(
        "Artifacts",
        "Everything a run wrote to disk, and what each file is for.",
    )

    reports, files, raw, predictions = st.tabs(
        ["Reports", "Files", "Raw JSON", "Predictions"]
    )
    with reports:
        _reports()
    with files:
        _files()
    with raw:
        _raw_json()
    with predictions:
        _predictions()


def _reports() -> None:
    paths = loader.markdown_reports()
    if not paths:
        ui.empty_state(
            "No markdown reports yet. `uv run embbench report` writes `results/report.md`."
        )
        return

    names = [p.name for p in paths]
    default = names.index("report.md") if "report.md" in names else 0
    chosen = st.selectbox("Report", names, index=default)
    text = loader.load_markdown(chosen)
    if text is None:
        ui.empty_state("That report could not be read.")
        return

    st.caption(
        "`report.md` is generated by `src/embbench/evaluation/report.py` from the same "
        "`result.json` files this dashboard reads, so the numbers cannot disagree."
    )
    st.download_button(
        "Download markdown", text.encode(), file_name=chosen, mime="text/markdown"
    )
    with st.container(border=True):
        st.markdown(text)


def _files() -> None:
    rows = loader.directory_listing()
    if not rows:
        ui.empty_state("`results/` is empty.")
        return

    frame = pd.DataFrame(rows)
    total = frame["bytes"].sum()

    cols = st.columns(3)
    cols[0].metric("Files", len(frame))
    cols[1].metric("Total size", loader.human_size(int(total)))
    cols[2].metric("Predictions share", _predictions_share(frame))

    query = st.text_input("Filter by path", "", placeholder="voyage, predictions, mteb-cache")
    view = frame if not query else frame[frame["file"].str.contains(query, case=False)]
    st.dataframe(
        view[["file", "kind", "size"]].sort_values("file"),
        hide_index=True,
        width="stretch",
        height=420,
        column_config={
            "file": st.column_config.TextColumn("Path (relative to results/)", width="large"),
            "kind": st.column_config.TextColumn("What it is", width="medium"),
            "size": st.column_config.TextColumn("Size"),
        },
    )
    st.caption(
        "`results/` is gitignored. These files are local to this machine and are not committed."
    )


def _predictions_share(frame: pd.DataFrame) -> str:
    total = frame["bytes"].sum()
    if total == 0:
        return "—"
    pred = frame[frame["file"].str.contains("predictions/")]["bytes"].sum()
    return f"{pred / total:.0%}"


def _raw_json() -> None:
    results = selected_results()
    if not results:
        ui.empty_state("No jobs to inspect.")
        return

    job_ids = sorted(res.spec.job_id for res in results)
    job_id = st.selectbox("Job", job_ids)
    kind = st.radio(
        "File",
        ["result.json", "manifest.json"],
        horizontal=True,
        help="`result.json` holds the scores. `manifest.json` holds the request that produced them.",
    )

    path = loader.results_dir() / job_id / kind
    if not path.exists():
        ui.empty_state(f"`{kind}` does not exist for this job.")
        return

    payload = loader.read_json_file(path)
    st.caption(f"`{path}` · {loader.human_size(path.stat().st_size)}")
    st.json(payload, expanded=2)


def _predictions() -> None:
    st.caption(
        "Prediction files hold the score every model gave every document for every query. "
        "They are hundreds of megabytes per job, so nothing is read until you ask for it."
    )

    results = selected_results()
    job_ids = sorted(
        res.spec.job_id for res in results if loader.list_predictions(res.spec.job_id)
    )
    if not job_ids:
        ui.empty_state("No prediction files were written for these jobs.")
        return

    job_id = st.selectbox("Job", job_ids, key="pred_job")
    entries = loader.list_predictions(job_id)
    listing = pd.DataFrame(
        [
            {"task": task, "size": loader.human_size(size), "bytes": size, "path": str(path)}
            for task, path, size in entries
        ]
    )
    st.dataframe(
        listing[["task", "size"]],
        hide_index=True,
        width="stretch",
        column_config={
            "task": st.column_config.TextColumn("Task"),
            "size": st.column_config.TextColumn("File size"),
        },
    )

    tasks = listing["task"].tolist()
    task = st.selectbox("Inspect one task", tasks, key="pred_task")
    row = listing[listing["task"] == task].iloc[0]
    size_mb = int(row["bytes"]) / (1024 * 1024)

    if size_mb > loader.PREDICTION_WARN_MB:
        st.warning(
            f"`{task}` is {loader.human_size(int(row['bytes']))}. Loading it parses the whole "
            "file into memory and can take several seconds.",
            icon=":material/warning:",
        )
    if not st.button(f"Load {task} ({loader.human_size(int(row['bytes']))})", type="primary"):
        return

    pred_path = Path(row["path"])
    with st.spinner(f"Parsing {task}…"):
        payload = loader.load_predictions(str(pred_path), pred_path.stat().st_mtime)
    runs = loader.prediction_runs(payload)
    if not runs:
        st.info(
            "This file carries no per-query rankings. STS tasks score sentence pairs directly, "
            "so there is nothing to rank.",
            icon=":material/info:",
        )
        return

    _render_run(runs, job_id, task)


def _render_run(runs: list, job_id: str, task: str) -> None:
    labels = [f"{subset} · {split}" for subset, split, _ in runs]
    label = st.selectbox("Subset and split", labels) if len(labels) > 1 else labels[0]
    _, _, queries = runs[labels.index(label)]

    query_ids = list(queries.keys())
    cols = st.columns(2)
    cols[0].metric("Queries", f"{len(query_ids):,}")
    cols[1].metric("Docs scored per query", f"{len(next(iter(queries.values()))):,}")

    query_id = st.selectbox("Query id", query_ids[:2000])
    top_n = st.slider("Show top", 5, 100, 20, step=5)

    ranked = sorted(queries[query_id].items(), key=lambda kv: kv[1], reverse=True)[:top_n]
    frame = pd.DataFrame(
        [{"rank": i, "doc_id": doc, "score": score} for i, (doc, score) in enumerate(ranked, 1)]
    )
    st.dataframe(
        frame,
        hide_index=True,
        width="stretch",
        column_config={
            "rank": st.column_config.NumberColumn("Rank", width="small"),
            "doc_id": st.column_config.TextColumn("Document id"),
            "score": st.column_config.NumberColumn("Similarity", format="%.4f"),
        },
    )
    st.caption(
        f"`{job_id}` on {task}. Document ids come from the MTEB corpus; the harness does not "
        "store the document text."
    )
